import "./globals.css";
import { Barlow_Semi_Condensed } from "next/font/google";

const barlow = Barlow_Semi_Condensed({ 
  subsets: ["latin"], 
  weight: ["400"]
});

export const metadata = {
  title: "DekSomBoon Massage",
  description: "Generated by create next app",
  icons: {
    icon: "/image/favicon.ico", 
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
      {children}
      </body>
    </html>
  );
}
