version: "3.9"
services:
  backend:
    build: ./backend
    container_name: dsb-backend
    ports:
      - "5000:5000"
    networks:
      - dsb-net

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE: http://localhost:5000
    container_name: dsb-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dsb-net

networks:
  dsb-net:
